/*
 * Copyright (c) 2017 Nicholas Corgan (n.corgan@gmail.com)
 *
 * Distributed under the MIT License (MIT) (See accompanying file LICENSE.txt
 * or copy at http://opensource.org/licenses/MIT)
 */
#ifndef PKSAV_GEN6_POKEPUFF_INVENTORY_H
#define PKSAV_GEN6_POKEPUFF_INVENTORY_H

#include <stdint.h>

#pragma pack(push, 1)

typedef enum
{
    PKSAV_GEN6_POKEPUFF_EMPTY = 0,
    PKSAV_GEN6_POKEPUFF_SWEET_BASIC,
    PKSAV_GEN6_POKEPUFF_MINT_BASIC,
    PKSAV_GEN6_POKEPUFF_CITRUS_BASIC,
    PKSAV_GEN6_POKEPUFF_MOCHA_BASIC,
    PKSAV_GEN6_POKEPUFF_SPICE_MASIC,
    PKSAV_GEN6_POKEPUFF_SWEET_FROSTED,
    PKSAV_GEN6_POKEPUFF_MINT_FROSTED,
    PKSAV_GEN6_POKEPUFF_MOCHA_FROSTED,
    PKSAV_GEN6_POKEPUFF_SPICE_FROSTED,
    PKSAV_GEN6_POKEPUFF_SWEET_FANCY,
    PKSAV_GEN6_POKEPUFF_MINT_FANCY,
    PKSAV_GEN6_POKEPUFF_CITRUS_FANCY,
    PKSAV_GEN6_POKEPUFF_MOCHA_FANCY,
    PKSAV_GEN6_POKEPUFF_SPICE_FANCY,
    PKSAV_GEN6_POKEPUFF_SWEET_DELUXE,
    PKSAV_GEN6_POKEPUFF_MINT_DELUXE,
    PKSAV_GEN6_POKEPUFF_CITRUS_DELUXE,
    PKSAV_GEN6_POKEPUFF_MOCHA_DELUXE,
    PKSAV_GEN6_POKEPUFF_SPICE_DELUXE,
    PKSAV_GEN6_POKEPUFF_WISH_SUPREME,
    PKSAV_GEN6_POKEPUFF_HONOR_SUPREME,
    PKSAV_GEN6_POKEPUFF_SPRING_SUPREME,
    PKSAV_GEN6_POKEPUFF_SUMMER_SUPREME,
    PKSAV_GEN6_POKEPUFF_FALL_SUPREME,
    PKSAV_GEN6_POKEPUFF_WINTER_SUPREME
} pksav_gen6_pokepuff_t;

#define PKSAV_GEN6_POKEPUFF_INVENTORY_SIZE 100

typedef struct
{
    uint8_t inventory[PKSAV_GEN6_POKEPUFF_INVENTORY_SIZE];
    uint32_t count;
} pksav_gen6_pokepuff_inventory_t;

#pragma pack(pop)

#endif /* PKSAV_GEN6_POKEPUFF_INVENTORY_H */
