/*!
 * @file    pksav/gen6/ribbons.h
 * @ingroup PKSav
 * @brief   Masks for getting and setting ribbons for Generation VI Pokémon
 *
 * Copyright (c) 2017 Nicholas Corgan (n.corgan@gmail.com)
 *
 * Distributed under the MIT License (MIT) (See accompanying file LICENSE.txt
 * or copy at http://opensource.org/licenses/MIT)
 */
#ifndef PKSAV_GEN6_RIBBONS_H
#define PKSAV_GEN6_RIBBONS_H

typedef enum
{
    PKSAV_GEN6_KALOS_CHAMPION_RIBBON_MASK = 0x01,
    PKSAV_GEN6_CHAMPION_RIBBON_MASK = 0x02,
    PKSAV_GEN6_SINNOH_CHAMP_RIBBON_MASK = 0x04,
    PKSAV_GEN6_BEST_FRIENDS_RIBBON_MASK = 0x08,
    PKSAV_GEN6_TRAINING_RIBBON_MASK = 0x10,
    PKSAV_GEN6_SKILLFUL_BATTLER_RIBBON_MASK = 0x20,
    PKSAV_GEN6_EXPERT_BATTLER_RIBBON_MASK = 0x40,
    PKSAV_GEN6_EFFORT_RIBBON_MASK = 0x80
} pksav_gen6_ribbon1_mask_t;

typedef enum
{
    PKSAV_GEN6_ALERT_RIBBON_MASK = 0x01,
    PKSAV_GEN6_SHOCK_RIBBON_MASK = 0x02,
    PKSAV_GEN6_DOWNCAST_RIBBON_MASK = 0x04,
    PKSAV_GEN6_CARELESS_RIBBON_MASK = 0x08,
    PKSAV_GEN6_RELAX_RIBBON_MASK = 0x10,
    PKSAV_GEN6_SNOOZE_RIBBON_MASK = 0x20,
    PKSAV_GEN6_SMILE_RIBBON_MASK = 0x40,
    PKSAV_GEN6_GORGEOUS_RIBBON_MASK = 0x80
} pksav_gen6_ribbon2_mask_t;

typedef enum
{
    PKSAV_GEN6_ROYAL_RIBBON_MASK = 0x01,
    PKSAV_GEN6_GORGEOUS_ROYAL_RIBBON_MASK = 0x02,
    PKSAV_GEN6_ARTIST_RIBBON_MASK = 0x04,
    PKSAV_GEN6_FOOTPRINT_RIBBON_MASK = 0x08,
    PKSAV_GEN6_RECORD_RIBBON_MASK = 0x10,
    PKSAV_GEN6_LEGEND_RIBBON_MASK = 0x20,
    PKSAV_GEN6_COUNTRY_RIBBON_MASK = 0x40,
    PKSAV_GEN6_NATIONAL_RIBBON_MASK = 0x80
} pksav_gen6_ribbon3_mask_t;

typedef enum
{
    PKSAV_GEN6_EARTH_RIBBON_MASK = 0x01,
    PKSAV_GEN6_WORLD_RIBBON_MASK = 0x02,
    PKSAV_GEN6_CLASSIC_RIBBON_MASK = 0x04,
    PKSAV_GEN6_PREMIER_RIBBON_MASK = 0x08,
    PKSAV_GEN6_EVENT_RIBBON_MASK = 0x10,
    PKSAV_GEN6_BIRTHDAY_RIBBON_MASK = 0x20,
    PKSAV_GEN6_SPECIAL_RIBBON_MASK = 0x40,
    PKSAV_GEN6_SOUVENIR_RIBBON_MASK = 0x80
} pksav_gen6_ribbon4_mask_t;

typedef enum
{
    PKSAV_GEN6_WISHING_RIBBON_MASK = 0x01,
    PKSAV_GEN6_BATTLE_CHAMPION_RIBBON_MASK = 0x02,
    PKSAV_GEN6_REGIONAL_CHAMPION_RIBBON_MASK = 0x04,
    PKSAV_GEN6_NATIONAL_CHAMPION_RIBBON_MASK = 0x08,
    PKSAV_GEN6_WORLD_CHAMPION_RIBBON_MASK = 0x10,
    PKSAV_GEN6_HOENN_CHAMPION_RIBBON_MASK = 0x80
} pksav_gen6_ribbon5_mask_t;

typedef enum
{
    PKSAV_GEN6_CONTEST_STAR_RIBBON_MASK = 0x01,
    PKSAV_GEN6_COOLNESS_MASTER_RIBBON_MASK = 0x02,
    PKSAV_GEN6_BEAUTY_MASTER_RIBBON_MASK = 0x04,
    PKSAV_GEN6_CUTENESS_MASTER_RIBBON_MASK = 0x08,
    PKSAV_GEN6_CLEVERNESS_MASTER_RIBBON_MASK = 0x10,
    PKSAV_GEN6_TOUGHNESS_MASTER_RIBBON_MASK = 0x20
} pksav_gen6_ribbon6_mask_t;

#endif /* PKSAV_GEN6_RIBBONS_H */
