/*
 * Copyright (c) 2017 Nicholas Corgan (n.corgan@gmail.com)
 *
 * Distributed under the MIT License (MIT) (See accompanying file LICENSE.txt
 * or copy at http://opensource.org/licenses/MIT)
 */
#ifndef PKSAV_GEN6_SUPER_TRAINING_DATA_H
#define PKSAV_GEN6_SUPER_TRAINING_DATA_H

#include <stdint.h>

typedef enum
{
    PKSAV_GEN6_SUPER_TRAINING_BAG_EMPTY = 0,
    PKSAV_GEN6_SUPER_TRAINING_BAG_HP_S,
    PKSAV_GEN6_SUPER_TRAINING_BAG_HP_M,
    PKSAV_GEN6_SUPER_TRAINING_BAG_HP_L,
    PKSAV_GEN6_SUPER_TRAINING_BAG_ATK_S,
    PKSAV_GEN6_SUPER_TRAINING_BAG_ATK_M,
    PKSAV_GEN6_SUPER_TRAINING_BAG_ATK_L,
    PKSAV_GEN6_SUPER_TRAINING_BAG_DEF_S,
    PKSAV_GEN6_SUPER_TRAINING_BAG_DEF_M,
    PKSAV_GEN6_SUPER_TRAINING_BAG_DEF_L,
    PKSAV_GEN6_SUPER_TRAINING_BAG_SPATK_S,
    PKSAV_GEN6_SUPER_TRAINING_BAG_SPATK_M,
    PKSAV_GEN6_SUPER_TRAINING_BAG_SPATK_L,
    PKSAV_GEN6_SUPER_TRAINING_BAG_SPDEF_S,
    PKSAV_GEN6_SUPER_TRAINING_BAG_SPDEF_M,
    PKSAV_GEN6_SUPER_TRAINING_BAG_SPDEF_L,
    PKSAV_GEN6_SUPER_TRAINING_BAG_SPEED_S,
    PKSAV_GEN6_SUPER_TRAINING_BAG_SPEED_M,
    PKSAV_GEN6_SUPER_TRAINING_BAG_SPEED_L,
    PKSAV_GEN6_SUPER_TRAINING_BAG_STRENGTH,
    PKSAV_GEN6_SUPER_TRAINING_BAG_TOUGHEN_UP,
    PKSAV_GEN6_SUPER_TRAINING_BAG_SWIFTNESS,
    PKSAV_GEN6_SUPER_TRAINING_BAG_BIG_SHOT,
    PKSAV_GEN6_SUPER_TRAINING_BAG_DOUBLE_UP,
    PKSAV_GEN6_SUPER_TRAINING_BAG_TEAM_FLARE,
    PKSAV_GEN6_SUPER_TRAINING_BAG_RESET,
    PKSAV_GEN6_SUPER_TRAINING_BAG_SOOTHING
} pksav_gen6_super_training_bag_t;

#define PKSAV_GEN6_SUPER_TRAINING_NUM_MISSIONS       30
#define PKSAV_GEN6_SUPER_TRAINING_BAG_INVENTORY_SIZE 12

#pragma pack(push, 1)

typedef struct
{
    float best_times[PKSAV_GEN6_SUPER_TRAINING_NUM_MISSIONS];
    uint32_t species_with_best_times[PKSAV_GEN6_SUPER_TRAINING_NUM_MISSIONS];
    uint8_t bag_inventory[PKSAV_GEN6_SUPER_TRAINING_BAG_INVENTORY_SIZE];
} pksav_gen6_super_training_data_t;

#pragma pack(pop)

#endif /* PKSAV_GEN6_SUPER_TRAINING_DATA_H */
