/*!
 * @file    pksav/common/nds_ribbons.h
 * @ingroup PKSav
 * @brief   Native storage for ribbons from Generation IV-V games.
 *
 * Copyright (c) 2017 Nicholas Corgan (n.corgan@gmail.com)
 *
 * Distributed under the MIT License (MIT) (See accompanying file LICENSE.txt
 * or copy at http://opensource.org/licenses/MIT)
 */
#ifndef PKSAV_COMMON_NDS_RIBBONS_H
#define PKSAV_COMMON_NDS_RIBBONS_H

typedef enum
{
    PKSAV_NDS_HOENN_COOL_RIBBON_MASK              = (1 << 0),
    PKSAV_NDS_HOENN_COOL_GREAT_RIBBON_MASK        = (1 << 1),
    PKSAV_NDS_HOENN_COOL_ULTRA_RIBBON_MASK        = (1 << 2),
    PKSAV_NDS_HOENN_COOL_MASTER_RIBBON_MASK       = (1 << 3),
    PKSAV_NDS_HOENN_BEAUTY_RIBBON_MASK            = (1 << 4),
    PKSAV_NDS_HOENN_BEAUTY_GREAT_RIBBON_MASK      = (1 << 5),
    PKSAV_NDS_HOENN_BEAUTY_ULTRA_RIBBON_MASK      = (1 << 6),
    PKSAV_NDS_HOENN_BEAUTY_MASTER_RIBBON_MASK     = (1 << 7),
    PKSAV_NDS_HOENN_CUTE_RIBBON_MASK              = (1 << 8),
    PKSAV_NDS_HOENN_CUTE_GREAT_RIBBON_MASK        = (1 << 9),
    PKSAV_NDS_HOENN_CUTE_ULTRA_RIBBON_MASK        = (1 << 10),
    PKSAV_NDS_HOENN_CUTE_MASTER_RIBBON_MASK       = (1 << 11),
    PKSAV_NDS_HOENN_SMART_RIBBON_MASK             = (1 << 12),
    PKSAV_NDS_HOENN_SMART_GREAT_RIBBON_MASK       = (1 << 13),
    PKSAV_NDS_HOENN_SMART_ULTRA_RIBBON_MASK       = (1 << 14),
    PKSAV_NDS_HOENN_SMART_MASTER_RIBBON_MASK      = (1 << 15),
    PKSAV_NDS_HOENN_TOUGH_RIBBON_MASK             = (1 << 16),
    PKSAV_NDS_HOENN_TOUGH_GREAT_RIBBON_MASK       = (1 << 17),
    PKSAV_NDS_HOENN_TOUGH_ULTRA_RIBBON_MASK       = (1 << 18),
    PKSAV_NDS_HOENN_TOUGH_MASTER_RIBBON_MASK      = (1 << 19),
    PKSAV_NDS_HOENN_CHAMPION_RIBBON_MASK          = (1 << 20),
    PKSAV_NDS_HOENN_WINNING_RIBBON_MASK           = (1 << 21),
    PKSAV_NDS_HOENN_VICTORY_RIBBON_MASK           = (1 << 22),
    PKSAV_NDS_HOENN_ARTIST_RIBBON_MASK            = (1 << 23),
    PKSAV_NDS_HOENN_EFFORT_RIBBON_MASK            = (1 << 24),
    PKSAV_NDS_HOENN_BATTLE_CHAMPION_RIBBON_MASK   = (1 << 25),
    PKSAV_NDS_HOENN_REGIONAL_CHAMPION_RIBBON_MASK = (1 << 26),
    PKSAV_NDS_HOENN_NATIONAL_CHAMPION_RIBBON_MASK = (1 << 27),
    PKSAV_NDS_HOENN_COUNTRY_RIBBON_MASK           = (1 << 28),
    PKSAV_NDS_HOENN_NATIONAL_RIBBON_MASK          = (1 << 29),
    PKSAV_NDS_HOENN_EARTH_RIBBON_MASK             = (1 << 30),
    PKSAV_NDS_HOENN_WORLD_RIBBON_MASK             = (1 << 31)
} pksav_nds_hoenn_ribbon_mask_t;

typedef enum
{
    PKSAV_NDS_SINNOH_CHAMP_RIBBON_MASK          = (1 << 0),
    PKSAV_NDS_SINNOH_ABILITY_RIBBON_MASK        = (1 << 1),
    PKSAV_NDS_SINNOH_GREAT_ABILITY_RIBBON_MASK  = (1 << 2),
    PKSAV_NDS_SINNOH_DOUBLE_ABILITY_RIBBON_MASK = (1 << 3),
    PKSAV_NDS_SINNOH_MULTI_ABILITY_RIBBON_MASK  = (1 << 4),
    PKSAV_NDS_SINNOH_PAIR_ABILITY_RIBBON_MASK   = (1 << 5),
    PKSAV_NDS_SINNOH_WORLD_ABILITY_RIBBON_MASK  = (1 << 6),
    PKSAV_NDS_SINNOH_ALERT_RIBBON_MASK          = (1 << 7),
    PKSAV_NDS_SINNOH_SHOCK_RIBBON_MASK          = (1 << 8),
    PKSAV_NDS_SINNOH_DOWNCAST_RIBBON_MASK       = (1 << 9),
    PKSAV_NDS_SINNOH_CARELESS_RIBBON_MASK       = (1 << 10),
    PKSAV_NDS_SINNOH_RELAX_RIBBON_MASK          = (1 << 11),
    PKSAV_NDS_SINNOH_SNOOZE_RIBBON_MASK         = (1 << 12),
    PKSAV_NDS_SINNOH_SMILE_RIBBON_MASK          = (1 << 13),
    PKSAV_NDS_SINNOH_GORGEOUS_RIBBON_MASK       = (1 << 14),
    PKSAV_NDS_SINNOH_ROYAL_RIBBON_MASK          = (1 << 15)
} pksav_nds_sinnoh_ribbon1_mask_t;

typedef enum
{
    PKSAV_NDS_SINNOH_GORGEOUS_ROYAL_RIBBON_MASK = (1 << 0),
    PKSAV_NDS_SINNOH_FOOTPRINT_RIBBON_MASK      = (1 << 1),
    PKSAV_NDS_SINNOH_RECORD_RIBBON_MASK         = (1 << 2),
    PKSAV_NDS_SINNOH_HISTORY_RIBBON_MASK        = (1 << 3),
    PKSAV_NDS_SINNOH_LEGEND_RIBBON_MASK         = (1 << 4),
    PKSAV_NDS_SINNOH_RED_RIBBON_MASK            = (1 << 5),
    PKSAV_NDS_SINNOH_GREEN_RIBBON_MASK          = (1 << 6),
    PKSAV_NDS_SINNOH_BLUE_RIBBON_MASK           = (1 << 7),
    PKSAV_NDS_SINNOH_FESTIVAL_RIBBON_MASK       = (1 << 8),
    PKSAV_NDS_SINNOH_CARNIVAL_RIBBON_MASK       = (1 << 9),
    PKSAV_NDS_SINNOH_CLASSIC_RIBBON_MASK        = (1 << 10),
    PKSAV_NDS_SINNOH_PREMIER_RIBBON_MASK        = (1 << 11)
} pksav_nds_sinnoh_ribbon2_mask_t;

typedef enum
{
    PKSAV_NDS_SINNOH_COOL_RIBBON_MASK          = (1 << 0),
    PKSAV_NDS_SINNOH_COOL_GREAT_RIBBON_MASK    = (1 << 1),
    PKSAV_NDS_SINNOH_COOL_ULTRA_RIBBON_MASK    = (1 << 2),
    PKSAV_NDS_SINNOH_COOL_MASTER_RIBBON_MASK   = (1 << 3),
    PKSAV_NDS_SINNOH_BEAUTY_RIBBON_MASK        = (1 << 4),
    PKSAV_NDS_SINNOH_BEAUTY_GREAT_RIBBON_MASK  = (1 << 5),
    PKSAV_NDS_SINNOH_BEAUTY_ULTRA_RIBBON_MASK  = (1 << 6),
    PKSAV_NDS_SINNOH_BEAUTY_MASTER_RIBBON_MASK = (1 << 7),
    PKSAV_NDS_SINNOH_CUTE_RIBBON_MASK          = (1 << 8),
    PKSAV_NDS_SINNOH_CUTE_GREAT_RIBBON_MASK    = (1 << 9),
    PKSAV_NDS_SINNOH_CUTE_ULTRA_RIBBON_MASK    = (1 << 10),
    PKSAV_NDS_SINNOH_CUTE_MASTER_RIBBON_MASK   = (1 << 11),
    PKSAV_NDS_SINNOH_SMART_RIBBON_MASK         = (1 << 12),
    PKSAV_NDS_SINNOH_SMART_GREAT_RIBBON_MASK   = (1 << 13),
    PKSAV_NDS_SINNOH_SMART_ULTRA_RIBBON_MASK   = (1 << 14),
    PKSAV_NDS_SINNOH_SMART_MASTER_RIBBON_MASK  = (1 << 15),
    PKSAV_NDS_SINNOH_TOUGH_RIBBON_MASK         = (1 << 16),
    PKSAV_NDS_SINNOH_TOUGH_GREAT_RIBBON_MASK   = (1 << 17),
    PKSAV_NDS_SINNOH_TOUGH_ULTRA_RIBBON_MASK   = (1 << 18),
    PKSAV_NDS_SINNOH_TOUGH_MASTER_RIBBON_MASK  = (1 << 19)
} pksav_nds_sinnoh_ribbon3_mask_t;

typedef enum
{
    PKSAV_NDS_UNOVA_GORGEOUS_ROYAL_RIBBON_MASK = (1 << 0),
    PKSAV_NDS_UNOVA_FOOTPRINT_RIBBON_MASK      = (1 << 1),
    PKSAV_NDS_UNOVA_RECORD_RIBBON_MASK         = (1 << 2),
    PKSAV_NDS_UNOVA_EVENT_RIBBON_MASK          = (1 << 3),
    PKSAV_NDS_UNOVA_LEGEND_RIBBON_MASK         = (1 << 4),
    PKSAV_NDS_UNOVA_WORLD_CHAMPION_RIBBON_MASK = (1 << 5),
    PKSAV_NDS_UNOVA_BIRTHDAY_RIBBON_MASK       = (1 << 6),
    PKSAV_NDS_UNOVA_SPECIAL_RIBBON_MASK        = (1 << 7),
    PKSAV_NDS_UNOVA_SOUVENIR_RIBBON_MASK       = (1 << 8),
    PKSAV_NDS_UNOVA_WISHING_RIBBON_MASK        = (1 << 9),
    PKSAV_NDS_UNOVA_CLASSIC_RIBBON_MASK        = (1 << 10),
    PKSAV_NDS_UNOVA_PREMIER_RIBBON_MASK        = (1 << 11)
} pksav_nds_unova_ribbon_mask_t;

#endif /* PKSAV_COMMON_NDS_RIBBONS_H */
